import type { Metadata } from "next";
import IntroPage from "./@intro/page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  intro
}: Readonly<{
  children: React.ReactNode;
  intro: React.ReactNode;
}>) {
  return (
    <>
        {intro}
        {children}
    </>
  );
}
